# Sentiment Analysis Project
In this notebook, I'll document my process of creating a machine learning model that analyzes Twitter messages and predicts their sentiment.

In [10]:
import contractions
import nltk
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from huggingface_hub import hf_hub_download
from gensim.models import KeyedVectors
from nltk.tokenize import TweetTokenizer
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Embedding, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tqdm import tqdm

In [2]:
data = pd.read_csv('Data/sentiment_data.csv')
data = data.dropna()
data.head()

   Unnamed: 0                                            Comment  Sentiment
0           0  lets forget apple pay required brand new iphon...          1
1           1  nz retailers don’t even contactless credit car...          0
2           2  forever acknowledge channel help lessons ideas...          2
3           3  whenever go place doesn’t take apple pay doesn...          0
4           4  apple pay convenient secure easy use used kore...          2

### Downloading GloVe Embeddings
GloVe embeddings are yet again, another way to capture word relationships. But I feel like their method of doing so is a step up from N-grams. N-grams are good at capturing local word sequences, but they're not so good at generalizing patterns, which is important for the model to actually apply its learning. For example, it might learn that the phrase "New York" has words that frequently appear together, and then learn that those words are related. Still, it won't generalize this pattern for unseen phrases like "New Jersey". 

In contrast, GloVe embeddings represent each word as a dense vector, which serves as a coordinate for its position in vector space. Words positioned close together have similar meanings or are used in similar contexts. So, the words new, york, and jersey might be located near each other in that space, reflecting their related geographic or contextual meanings. GloVe embeddings effectively supply the model with a foundational understanding of word relationships so that it won’t have to learn word meanings and relationships from scratch.

In [3]:
repo_id = "fse/glove-twitter-200"   # repo name on Hugging Face
file1 = "glove-twitter-200.model"
file2 = "glove-twitter-200.model.vectors.npy"
    
# Download both
model_file = hf_hub_download(repo_id=repo_id, filename=file1)
vectors_file = hf_hub_download(repo_id=repo_id, filename=file2)
    
print("Downloaded model:", model_file)
print("Downloaded vectors:", vectors_file)

glove_model = KeyedVectors.load(model_file)

Downloaded model: /home/saniaa/.cache/huggingface/hub/models--fse--glove-twitter-200/snapshots/72f480c107aaa58b9474ddaf45d13db2e34fa166/glove-twitter-200.model
Downloaded vectors: /home/saniaa/.cache/huggingface/hub/models--fse--glove-twitter-200/snapshots/72f480c107aaa58b9474ddaf45d13db2e34fa166/glove-twitter-200.model.vectors.npy

### Tokenizing:
Since every word is mapped to a vector, I have to split each message into its individual words. This process is called **tokenizing**. Since the GloVe model wasn't trained on my data, some of the words in my dataset may not appear in its vocabulary. However, as long as there aren't that many, dropping them won't affect determining the sentiment of the text.

In [4]:
twtk = TweetTokenizer()

def make_token(sen):
    sen = contractions.fix(sen)
    return twtk.tokenize(sen)

data['Tokens'] = [make_token(sentence) for sentence in tqdm(data['Comment'])]
data.head()

100%|████████████████████████████████████████████████████████████████████████| 240928/240928 [00:15<00:00, 15220.71it/s]

,Unnamed: 0,Comment,Sentiment,Tokens
0,0,lets forget apple pay required brand new iphon...,1,"[let, us, forget, apple, pay, required, brand,..."
1,1,nz retailers don’t even contactless credit car...,0,"[nz, retailers, do, not, even, contactless, cr..."
2,2,forever acknowledge channel help lessons ideas...,2,"[forever, acknowledge, channel, help, lessons,..."
3,3,whenever go place doesn’t take apple pay doesn...,0,"[whenever, go, place, does, not, take, apple, ..."
4,4,apple pay convenient secure easy use used kore...,2,"[apple, pay, convenient, secure, easy, use, us..."

### Creating Token Vocabulary and Mapping to Vectors:
For the model to be able to process each message, I created a **token vocabulary**, which is a list of all unique words in the dataset. Each token was mapped to its vector so the model can work with numbers instead of raw text.

In [5]:
#making dictionaries so that each word maps to it's vector

def make_token_vocab(sequences):
    token_vocab = set()  
    for seq in tqdm(sequences):
        for token in seq:
            if token in token_vocab:
                continue
            if token not in glove_model:
                continue
            token_vocab.add(token)
    return list(token_vocab)  
   
def make_token_indexes():
    indexes = []
    for index, token in tqdm(enumerate(token_vocab)):
        indexes.append(index + 1)
    return indexes

def make_vector_vocab():
    vector_vocab = []  
    for token in tqdm(token_vocab):
        vector_vocab.append(glove_model[token])
    return vector_vocab

token_vocab = make_token_vocab(data['Tokens'])
token_indexes = make_token_indexes()
vector_vocab = make_vector_vocab()

100%|███████████████████████████████████████████████████████████████████████| 240928/240928 [00:00<00:00, 419643.94it/s]
62681it [00:00, 3046280.77it/s]
100%|█████████████████████████████████████████████████████████████████████████| 62681/62681 [00:00<00:00, 746710.05it/s]

### Padding:
A special `<PAD>` token is added at index 0 with a vector of zeros. This token is used to fill sequences that are shorter than the maximum length, ensuring all input sequences have the same size. Finally, two dictionaries are created: one mapping tokens to indices (token_index_dict) and one mapping tokens to vectors

In [6]:
padding_token = '<PAD>'
padding_index = 0
padding_vector = np.zeros_like(vector_vocab[0])

token_vocab = [padding_token] + token_vocab
token_indexes = [padding_index] + token_indexes
vector_vocab = [padding_vector] + vector_vocab

token_index_dict = dict(zip(token_vocab, token_indexes))
token_vector_dict = dict(zip(token_vocab, vector_vocab))

In [7]:
#truncating message lengths
max_length = 100

data['Length'] = [len(tokens) for tokens in data['Tokens']]
data = data[data['Length'] < max_length]

### Making Matrices:
I converted each token in a message to its corresponding index using the token–index dictionary. This dictionary serves as a look-up table, with each token mapped to a unique integer that the model can use to reference its corresponding vector. I also padded/truncated sequences to a fixed max_length so that all inputs have the same size. This is because I plan to use a neural network, and they require inputs of the same length for batch processing. Batch-processing speeds up the training process by allowing the model to process multiple inputs at once. Finally, the token vectors are stored in embedding_matrix and the sequences of indices are stored in indices_matrix, ready to feed into the model.

In [8]:
def make_indices(seq):
    sequence = []
    for token in seq:
        if token not in glove_model:
            continue
        else:
            token = token_index_dict[token]
            sequence.append(token)
    return sequence

data['Indices'] = [make_indices(seq) for seq in tqdm(data['Tokens'])] 

def pad_sequence(seq):
    if len(seq) > max_length:
        seq = seq[:max_length]
    elif len(seq) < max_length:
        seq = seq + ([0] * (max_length - len(seq)))
    return seq
    
data['Indices'] = [pad_sequence(seq) for seq in data['Indices']]

embedding_matrix = np.array(vector_vocab)
indices_matrix = np.array(data['Indices'].tolist())
data.head()

100%|███████████████████████████████████████████████████████████████████████| 240680/240680 [00:02<00:00, 109418.25it/s]

,Unnamed: 0,Comment,Sentiment,Tokens,Length,Indices
0,0,lets forget apple pay required brand new iphon...,1,"[let, us, forget, apple, pay, required, brand,...",35,"[524, 16805, 49256, 53746, 37456, 57052, 23128..."
1,1,nz retailers don’t even contactless credit car...,0,"[nz, retailers, do, not, even, contactless, cr...",20,"[35703, 54041, 32801, 44794, 48069, 40212, 541..."
2,2,forever acknowledge channel help lessons ideas...,2,"[forever, acknowledge, channel, help, lessons,...",16,"[62514, 14706, 16042, 3042, 48326, 1925, 3685,..."
3,3,whenever go place doesn’t take apple pay doesn...,0,"[whenever, go, place, does, not, take, apple, ...",58,"[32610, 58619, 61937, 53029, 44794, 1462, 5374..."
4,4,apple pay convenient secure easy use used kore...,2,"[apple, pay, convenient, secure, easy, use, us...",14,"[53746, 37456, 59596, 46194, 44086, 27981, 156..."

In [11]:
X = indices_matrix
y = data['Sentiment'].values

# Split into 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)

# Convert labels to tf.int32
y_train = tf.cast(y_train, tf.int32)
y_test = tf.cast(y_test, tf.int32)

I0000 00:00:1761918287.782631    1444 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1765 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

### LSTM Model:
Originally, I wanted to use an **RNN model**, but I learned that RNNs don't do well with "remembering" all aspects of a sentence. As sentences get longer, RNNs tend to forget earlier information to make room for more recent inputs. This can remove the context necessary to denote the sentiment of the text.

I settled on an **LSTM model** because, unlike standard neural networks, they maintain memory. I settled on an LSTM model because, unlike standard neural networks, they maintain memory. They do this through gates that control what information to keep, forget, or output at each time step. This ability to remember previous words also helps the model understand word order, which can be vital to understanding the sentence's meaning. In the phrase "I am happy", witching the order to "Am I happy" changes the sentiment entirely.

### Embedding Layer:
**trainable = False**: I froze embeddings during training because I didn't want the model to change the pre-trained meanings of words
**mask_zero = True**: makes it so the model ignores padding tokens

### LSTM Layer:
**model.add(layers.LSTM(64))**: I chose 64 for the hidden-state size because I didn't want to use too much memory or risk overfitting the dataset.

### Dense Layer:
**model.add(layers.Dense(3, activation='softmax'))**: A Dense layer is just a layer where every neuron is fully connected to the neurons in the previous layer. So, it combines all the learned information to make a final decision. Additionally, I chose 3 units because there are 3 sentiment classes: positive, negative, and neutral, and I used the softmax as the activation function, which calculates the output. Softmax converts the dense layers' outputs into the probabilities of each class.

In [12]:
def make_model():
    model = keras.Sequential()
    model.add(layers.Embedding(
        input_dim = len(token_vocab),
        output_dim = 200,
        weights = [embedding_matrix],  
        trainable = False,             
        mask_zero = True
    ))
    model.add(layers.LSTM(32, use_cudnn=False))
    model.add(layers.Dense(3, activation = 'softmax'))

    return model

model = make_model()

model.compile(
    optimizer = keras.optimizers.Adam(learning_rate=0.0001),
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)

print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │    12,536,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,536,400 (47.82 MB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 12,536,400 (47.82 MB)

None

In [13]:
model_history = model.fit(
    X_train, y_train,
    batch_size = 256,
    epochs = 10,
    verbose = 1,
    validation_data = (X_test, y_test),
)

Epoch 1/10

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1761918310.217230    1599 service.cc:152] XLA service 0x7fbb84004600 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1761918310.217633    1599 service.cc:160]   StreamExecutor device (0): NVIDIA GeForce RTX 3050 Laptop GPU, Compute Capability 8.6
2025-10-31 09:45:10.334004: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1761918310.705323    1599 cuda_dnn.cc:529] Loaded cuDNN version 91002

  3/753 ━━━━━━━━━━━━━━━━━━━━ 44s 60ms/step - accuracy: 0.2973 - loss: 1.1579

I0000 00:00:1761918313.292130    1599 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

753/753 ━━━━━━━━━━━━━━━━━━━━ 59s 73ms/step - accuracy: 0.5509 - loss: 0.9452 - val_accuracy: 0.6137 - val_loss: 0.8545
Epoch 2/10
753/753 ━━━━━━━━━━━━━━━━━━━━ 52s 69ms/step - accuracy: 0.6380 - loss: 0.8198 - val_accuracy: 0.6491 - val_loss: 0.7990
Epoch 3/10
753/753 ━━━━━━━━━━━━━━━━━━━━ 56s 74ms/step - accuracy: 0.6609 - loss: 0.7785 - val_accuracy: 0.6661 - val_loss: 0.7700
Epoch 4/10
753/753 ━━━━━━━━━━━━━━━━━━━━ 56s 75ms/step - accuracy: 0.6756 - loss: 0.7519 - val_accuracy: 0.6778 - val_loss: 0.7474
Epoch 5/10
753/753 ━━━━━━━━━━━━━━━━━━━━ 58s 77ms/step - accuracy: 0.6874 - loss: 0.7310 - val_accuracy: 0.6875 - val_loss: 0.7295
Epoch 6/10
753/753 ━━━━━━━━━━━━━━━━━━━━ 59s 79ms/step - accuracy: 0.6970 - loss: 0.7134 - val_accuracy: 0.6957 - val_loss: 0.7152
Epoch 7/10
753/753 ━━━━━━━━━━━━━━━━━━━━ 58s 77ms/step - accuracy: 0.7054 - loss: 0.6979 - val_accuracy: 0.7006 - val_loss: 0.7021
Epoch 8/10
753/753 ━━━━━━━━━━━━━━━━━━━━ 62s 82ms/step - accuracy: 0.7124 - loss: 0.6841 - val_accuracy: 0.7090 - val_loss: 0.6915
Epoch 9/10
753/753 ━━━━━━━━━━━━━━━━━━━━ 62s 83ms/step - accuracy: 0.7193 - loss: 0.6717 - val_accuracy: 0.7144 - val_loss: 0.6799
Epoch 10/10
753/753 ━━━━━━━━━━━━━━━━━━━━ 62s 82ms/step - accuracy: 0.7258 - loss: 0.6601 - val_accuracy: 0.7210 - val_loss: 0.6693

### Reflection:
So...Switching models didn't yield the results I expected. The model actually did worse on both training and testing/validation data. However, training accuracy and validation accuracy are really close, ensuring that the model is definitely not overfitting. I think if I increase the number of training iterations, the accuracy will continue to increase consistently! My only problem is that training takes so long. I'm going to research if there are any ways to speed up the process.